name: Termius SSH Session

on:
  workflow_dispatch: # Actions tab-il ninnu manually run cheyyan

jobs:
  ssh-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH Connection (tmate)
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false # Ellavarum connection accept cheyyan
          
